site_name: Unit API
plugins:
  - search
#  - markdownextradata
#  - mkdocs_pymdownx_material_extras
  - codeinclude:
      title_mode: pymdownx.tabbed
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'teal'
  font: false
  logo: 'assets/logo.svg'
  favicon: 'assets/logo.ico'
repo_name: 'unit-api'
repo_url: 'https://github.com/raynigon/unit-api'
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
nav:
  - Home: index.md
  - Java:
      - General: java/index.md
      - Jackson: java/jackson.md
  - Spring Boot:
      - General: spring-boot/index.md
      - Jackson: spring-boot/jackson.md
      - JPA: spring-boot/jpa.md
      - Springdoc: spring-boot/springdoc.md
  - Kotlin: kotlin/index.md
  #- Examples: examples.md
  - JavaDoc: javadoc-ref.md
  - Contribution: contribution.md
extra:
  latest_version: 2.0.1
