site_name: Unit API
plugins:
  - search
  - codeinclude
  - markdownextradata
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'teal'
  font: false
  logo: 'logo.svg'
  favicon: 'logo.ico'
repo_name: 'unit-api'
repo_url: 'https://github.com/raynigon/unit-api'
markdown_extensions:
  - admonition
  - codehilite:
      linenums: False
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed
nav:
  - Home: index.md
  - Quickstart:
      - Jackson: quickstart/jackson.md
      - Spring Boot: quickstart/spring-boot.md
      - Kotlin: quickstart/kotlin.md
  - Modules:
      - Jackson Module: modules/jackson-module.md
      - Jackson Starter: modules/jackson-starter.md
      - Jpa Starter: modules/jpa-starter.md
      - Springdoc Starter: modules/springdoc-starter.md
      - Kotlin Module: modules/kotlin-module.md
  - Contribution: contribution.md
extra:
  latest_version: 1.0.1
