name: CI - PR
on:
  - pull_request

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Setup Java JDK"
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 17
          distribution: adopt
      - name: Kotlin Linter
        uses: eskatos/gradle-command-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef
        with:
          arguments: ktlintCheck
      - name: Checkstyle Linter
        uses: eskatos/gradle-command-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef
        with:
          arguments: checkstyleMain
      - name: PMD Linter
        uses: eskatos/gradle-command-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef
        with:
          arguments: pmdMain
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        if: github.actor != 'dependabot[bot]'
        with:
          path: '**/checkstyle/main.xml'
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          tool: spotbugs
          project-token: ${{ secrets.CODACY_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Setup Java JDK"
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 17
          distribution: adopt
      - name: Ktlint
        uses: eskatos/gradle-command-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef
        with:
          arguments: ktlintCheck
      - name: Unit Tests
        uses: eskatos/gradle-command-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef
        with:
          arguments: test
      - name: Codacy Publish
        uses: codacy/codacy-coverage-reporter-action@master
        if: github.actor != 'dependabot[bot]'
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}

  javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Setup Java JDK"
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 17
          distribution: adopt
      - name: Generate javadoc
        uses: eskatos/gradle-command-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef
        with:
          arguments: globalJavadoc

  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip3 install -r requirements.txt
      - run: mkdocs build -d build/site/
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: "Website"
          path: "build/site/"

  owasp:
    name: "OWASP check"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: "owasp-check-${{ github.ref }}"
      cancel-in-progress: true
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3
      - name: "Setup Java JDK"
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 17
          distribution: adopt
      - name: Cache Dependency Database
        uses: actions/cache@v3
        with:
          path: "~/.gradle/dependency-check-data/"
          key: "owasp-check"
      - name: "Execute dependencyCheckUpdate"
        uses: eskatos/gradle-command-action@v2.3.3
        continue-on-error: true
        with:
          arguments: dependencyCheckUpdate
      - name: "Execute dependencyCheckAnalyze"
        uses: eskatos/gradle-command-action@v2.3.3
        continue-on-error: true
        with:
          arguments: dependencyCheckAnalyze
      - id: "eval"
        name: "Evaluate OWASP report"
        uses: raynigon/gradle-owasp-parser@main
        with:
          fail_on_vulnerabilities: "true"
          path_report: "build/reports/dependency-check-report.json"
          path_build_gradle: "build.gradle"
      - name: Add comment to PR
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "${{ steps.eval.outputs.report_markdown }}"
          comment_tag: 'Comment-ID: owasp-report-${{ github.ref }}'